FROM ubuntu:16.04

RUN apt-get update && apt install --no-install-recommends --no-install-suggests -y  \
	g++ \
	valgrind \
	make \
	git \
	vim \
	xorg \
	libxext-dev \
	zlib1g-dev \
	libbsd-dev \
	build-essential \
	manpages-dev \
	&& rm -rf /var/lib/apt/lists/*